### ISSUE TITLE
Import difficulties with some level backends

### ISSUE THREAD

**Issue by kloboves** [yjs/y-leveldb#11]
**Describe the bug**
I was trying to use y-leveldb with 'level-rocksdb' backend. This module seems to have native import dependencies which somehow makes things more difficult. Please excuse my ignorance as I am quite new to Javascript / NodeJS.

My current toolchain setup is similar to the examples provided (rollup bundler, with plugins chain: resolve, commonjs, typescript, terser).

The fundamental problem relates to the use of import vs require() to import level libraries:

1) const level = require('level-rocksdb')
When importing level like this, things seem to work out (plugins don't touch the require command, and node.js is able to find the library and the corresponding native imports).

2) import level from 'level'
When importing level like this, it seems the 'resolve' plugin somehow tries to pack the whole 'level' library into the bundle, and breaking the native import mechanism. y-leveldb.js is importing level this way. I suspect that this works for "level-mem" (because there are no native imports) but not for other backends.

The problem: y-leveldb.js imports a `defaultLevel` using option (2), which causes problems when the default backend chosen is not "level-mem". Even when the user imports their own level backend correctly (with require), because y-leveldb.js is importing a version of level with mechanism (2) it always leads to the NodeJS trying to import native modules incorrectly and the binary crashing.

Possible solutions:
a) Remove the defaultLevel import in y-leveldb.js completely, and let the user import level however they want in their environment (user must specify the level instance in the constructor to the persistence object)

b) Workaround: It seems if we blacklist 'level' module from the resolve plugin it doesn't break the native imports and somehow translates the import into a require():

From rollup.config.js:
```
	plugins: [
		resolve({
			resolveOnly: name => name != 'level'
		}),
```

**To Reproduce**
Use y-leveldb with 'level-rocksdb'.

**Environment Information**
Node:
yjs@13.5.36
y-leveldb@0.1.1
level@^6.0.1
level-rocksdb@5.0.0
rocksdb@5.2.1

**Comment by kloboves** [comment]
Note: Also please note that in all examples on 'Level' repos they import level using require not import.

**Comment by dmonad** [comment]
Usually, you don't bundle nodejs applications. `level` has imports of native modules that can't be bundled. 

I think supporting bundling is out of scope for y-leveldb.. Hope you understand..
