### ISSUE TITLE
Directory traversal Vulnerability found

### ISSUE THREAD

**Issue by ChoudharyS** [yjs/y-leveldb#2]
If `options.namespace` is set to '..' or '/'. attacker can write into outside `options.dir` directories. 

Ex1:
https://github.com/y-js/y-websockets-server/blob/v9.2.1/src/server.js#L44-L45
If user input room as '..', they can write into directories outside 'y-leveldb-databases'.

Ex2:
https://github.com/FujitsuLaboratories/cattaz/pull/6#issuecomment-351585960

**Comment by dmonad** [comment]
This is finally fixed :sweat_smile:
